(function(){
  'use strict';
  var THEMES=[
    {name:'Lunar Command',desc:'A moonbase under siege, with robots defending the crater rail.',bg1:'#173d67',bg2:'#071321',path:'#d9f7ff',accent:'#42cfff',deco:'moonbase'},
    {name:'Xeno Jungle',desc:'An alien greenhouse overflowing with hostile bioluminescent plants.',bg1:'#123e4d',bg2:'#071b24',path:'#b7ffe7',accent:'#48e7bb',deco:'alienplant'},
    {name:'Robot Foundry',desc:'A massive automated factory where assembly lines become the battlefield.',bg1:'#27435b',bg2:'#0b1825',path:'#d7f4ff',accent:'#54bfff',deco:'robotfactory'},
    {name:'Xeno Laboratory',desc:'A research facility full of containment pods, scanners and escaped specimens.',bg1:'#27365e',bg2:'#100d28',path:'#e5d8ff',accent:'#a96cff',deco:'alienlab'},
    {name:'Orbital Dock',desc:'A launch platform above Earth where alien craft keep slipping through the perimeter.',bg1:'#163f70',bg2:'#050e20',path:'#dff8ff',accent:'#5dd9ff',deco:'ufohangar'},
    {name:'Crystal Moon',desc:'A frozen moon split by luminous alien crystal formations.',bg1:'#244e69',bg2:'#0a1a2a',path:'#d7ffff',accent:'#65eaff',deco:'crystal'},
    {name:'Terraformer Yard',desc:'Robot terraforming machines battle aliens around a half-built colony.',bg1:'#3b4b62',bg2:'#111a24',path:'#f1f7ff',accent:'#8ae7ff',deco:'terraformer'},
    {name:'Scrap City',desc:'A dense robot salvage district packed with wrecked machines and power cores.',bg1:'#31455e',bg2:'#0b1420',path:'#e5f6ff',accent:'#73c9ff',deco:'robotdock'},
    {name:'Bio Reactor',desc:'An alien bio-energy station where the walls themselves seem alive.',bg1:'#234b48',bg2:'#071c1b',path:'#cffff1',accent:'#5ff2c8',deco:'bioreactor'},
    {name:'UFO Crash Site',desc:'A smoking impact zone littered with alien wreckage and emergency beacons.',bg1:'#4a425d',bg2:'#171222',path:'#f6e9ff',accent:'#d28cff',deco:'crashsite'},
    {name:'Ice Relay',desc:'A frozen communications relay surrounded by hostile alien ice growths.',bg1:'#40708a',bg2:'#102637',path:'#fff',accent:'#8beaff',deco:'icerelay'},
    {name:'Alien Hive',desc:'The entrance to an enormous subterranean alien hive.',bg1:'#3e3158',bg2:'#120b20',path:'#f2d7ff',accent:'#d45cff',deco:'hive'},
    {name:'Solar Array',desc:'A robot power field beneath huge solar collectors.',bg1:'#365b70',bg2:'#101d29',path:'#f7fbff',accent:'#7bdfff',deco:'solar'},
    {name:'Defense Ring',desc:'A fortified orbital defense ring with turrets watching every approach.',bg1:'#234f73',bg2:'#071522',path:'#d8f7ff',accent:'#3dc8ff',deco:'defense'},
    {name:'Alien Garden',desc:'A beautiful but deadly alien ecosystem growing around old robots.',bg1:'#265b54',bg2:'#071b18',path:'#d4ffe9',accent:'#58efb8',deco:'alienplant'},
    {name:'Core Chamber',desc:'The glowing reactor heart of the robot colony.',bg1:'#33466b',bg2:'#0c1020',path:'#e4edff',accent:'#8c7cff',deco:'reactor'}
  ];
  function replaceVisibleText(){var w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),n;while(n=w.nextNode()){if(!n.nodeValue.trim())continue;n.nodeValue=n.nodeValue.replace(/Pantry Panic/g,'Robots vs Aliens').replace(/pantry panic/g,'Robots vs Aliens').replace(/formerly Pantry Panic/g,'').replace(/larder/gi,'sector').replace(/crumbs?/gi,'credits').replace(/jars?/gi,'energy cells');}}
  function applyMapThemes(){if(!window.MAPS||!Array.isArray(window.MAPS))return false;window.MAPS.forEach(function(m,i){var t=THEMES[i%THEMES.length];m.theme={bg1:t.bg1,bg2:t.bg2,path:t.path,accent:t.accent,deco:t.deco};if(i<THEMES.length){m.name=t.name;m.desc=t.desc;}});return true;}
  var oldDeco=window.decoIcon;
  function decoIcon(g,kind,x,y,r,col){if(!g)return;g.save();g.translate(x,y);g.globalAlpha=.72;g.fillStyle=col||'#61d9ff';g.strokeStyle=col||'#61d9ff';g.lineWidth=Math.max(1,r*.08);var c=col||'#61d9ff';function glow(){g.shadowColor=c;g.shadowBlur=Math.max(4,r*.35)}function box(w,h,rad){g.beginPath();g.roundRect(-w,-h,w*2,h*2,rad);g.fill();g.stroke()}glow();
    if(kind==='moonbase'){g.fillStyle='#8ea7bd';g.fillRect(-r*.8,-r*.2,r*1.6,r*.85);g.fillStyle='#17314b';g.fillRect(-r*.58,-r*.05,r*.36,r*.42);g.fillRect(r*.08,-r*.05,r*.36,r*.42);g.strokeStyle='#7ce7ff';g.beginPath();g.arc(0,-r*.2,r*.9,Math.PI,0);g.stroke()}
    else if(kind==='alienplant'){g.strokeStyle='#69ffd0';g.lineWidth=r*.12;g.beginPath();g.moveTo(0,r);g.quadraticCurveTo(-r*.1,0,-r*.55,-r*.8);g.moveTo(0,r);g.quadraticCurveTo(r*.15,0,r*.65,-r*.95);g.stroke();g.fillStyle='#48e7bb';for(var i=0;i<5;i++){var a=-1.8+i*.8;g.beginPath();g.ellipse(Math.cos(a)*r*.45,Math.sin(a)*r*.45,r*.25,r*.12,a,0,6.283);g.fill()}}
    else if(kind==='robotfactory'){g.fillStyle='#536d82';g.fillRect(-r,-r*.45,r*2,r*1.45);g.fillStyle='#182b3c';g.fillRect(-r*.6,-r*.15,r*.35,r*.65);g.fillRect(r*.1,-r*.15,r*.35,r*.65);g.fillStyle='#61dfff';g.fillRect(-r*.15,-r*.9,r*.3,r*.35);g.fillStyle='#536d82';g.fillRect(-r*.75,-r*.95,r*.35,r*.55);g.fillRect(r*.4,-r*1.05,r*.35,r*.65)}
    else if(kind==='alienlab'){g.fillStyle='#334966';box(r*.72,r*.8,r*.18);g.fillStyle='#8cecff';g.beginPath();g.arc(0,-r*.1,r*.48,0,6.283);g.fill();g.fillStyle='#8b5cf6';g.globalAlpha=.7;g.beginPath();g.arc(0,-r*.1,r*.28,0,6.283);g.fill()}
    else if(kind==='ufohangar'||kind==='crashsite'){g.fillStyle='#71899d';g.beginPath();g.ellipse(0,r*.2,r*1.05,r*.38,0,0,6.283);g.fill();g.stroke();g.fillStyle='#75eaff';g.beginPath();g.ellipse(0,0,r*.55,r*.35,0,0,6.283);g.fill();g.fillStyle='#d65cff';g.fillRect(-r*.65,r*.22,r*1.3,r*.1)}
    else if(kind==='crystal'){g.fillStyle='#8de9ff';g.beginPath();g.moveTo(-r*.7,r);g.lineTo(-r*.3,-r*.8);g.lineTo(-r*.05,-r*.15);g.lineTo(r*.25,-r*1.05);g.lineTo(r*.75,r);g.closePath();g.fill();g.strokeStyle='#e8ffff';g.stroke()}
    else if(kind==='terraformer'||kind==='solar'){g.fillStyle='#7f95a7';g.fillRect(-r*.95,-r*.15,r*1.9,r*.3);g.fillRect(-r*.12,-r*.8,r*.24,r*1.6);g.fillStyle='#2b6e9b';for(var q=-1;q<=1;q+=2){g.save();g.rotate(q*.25);g.fillRect(q*r*.45,-r*.75,r*.65,r*.3);g.restore()}}
    else if(kind==='robotdock'||kind==='defense'){g.strokeStyle='#61dfff';g.lineWidth=r*.16;g.beginPath();g.arc(0,0,r*.8,0,6.283);g.stroke();g.fillStyle='#3d607d';g.fillRect(-r*.18,-r*.18,r*.36,r*.36);for(var z=0;z<4;z++){var a=z*Math.PI/2;g.fillRect(Math.cos(a)*r*.62-r*.1,Math.sin(a)*r*.62-r*.1,r*.2,r*.2)}}
    else if(kind==='bioreactor'||kind==='reactor'){g.fillStyle='#263d58';box(r*.65,r*.8,r*.18);g.fillStyle='#59f4cf';g.beginPath();g.arc(0,0,r*.42,0,6.283);g.fill();g.fillStyle='#dff';g.globalAlpha=.8;g.beginPath();g.arc(-r*.13,-r*.12,r*.1,0,6.283);g.fill()}
    else if(kind==='icerelay'){g.fillStyle='#cdefff';g.beginPath();g.moveTo(-r*.75,r);g.lineTo(-r*.3,-r*.8);g.lineTo(r*.1,r*.15);g.lineTo(r*.55,-r*.9);g.lineTo(r*.8,r);g.closePath();g.fill();g.stroke()}
    else if(kind==='hive'){g.fillStyle='#6d4c8e';g.beginPath();g.arc(0,0,r,0,6.283);g.fill();g.fillStyle='#0a1524';g.beginPath();g.arc(0,0,r*.35,0,6.283);g.fill();g.strokeStyle='#df6cff';g.stroke()}
    else if(oldDeco){g.restore();oldDeco(g,kind,x,y,r,col);return}g.shadowBlur=0;g.restore();}
  window.decoIcon=decoIcon;
  function rebuildDecos(){if(!window.MAPS||typeof window.curMap==='undefined')return;var t=THEMES[(window.curMap||0)%THEMES.length];window.mapDecos=[];var count=14,seed=((window.curMap||0)+7)*9137;function rnd(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}for(var i=0;i<count;i++){var gx=Math.floor(rnd()*(window.GW||24)),gy=Math.floor(rnd()*(window.GH||15)),x=(gx+.5)*(window.CELL||32),y=(gy+.5)*(window.CELL||32);window.mapDecos.push({x:x,y:y,r:(window.CELL||32)*(.25+rnd()*.14),flip:rnd()<.5?-1:1,kind:t.deco});}}
  window.bakeMapDecos=rebuildDecos;
  function rebuildLandmark(){if(typeof window.curMap==='undefined')return;var t=THEMES[(window.curMap||0)%THEMES.length];window.mapLandmark=null;var cs=[[4,3],[19,3],[4,11],[19,11],[11,2],[11,12],[2,7],[21,7],[8,2],[15,2],[8,12],[15,12]];for(var i=0;i<cs.length;i++){var x=cs[i][0],y=cs[i][1],k=x+','+y;if(window.blockedCells&&window.blockedCells[k])continue;window.mapLandmark={x:(x+.5)*(window.CELL||32),y:(y+.5)*(window.CELL||32),r:(window.CELL||32)*1.35,kind:t.deco};if(window.blockedCells)window.blockedCells[k]=1;break;}}
  window.bakeLandmark=rebuildLandmark;
  function drawTitleBg(t){var c=document.getElementById('titleBg');if(!c)return;var w=c.clientWidth,h=c.clientHeight;if(!w||!h)return;var dpr=Math.min(2,window.devicePixelRatio||1);if(c.width!==w*dpr||c.height!==h*dpr){c.width=w*dpr;c.height=h*dpr}var g=c.getContext('2d');g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,w,h);var sky=g.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#06152b');sky.addColorStop(.52,'#0d3970');sky.addColorStop(1,'#eaf9ff');g.fillStyle=sky;g.fillRect(0,0,w,h);for(var i=0;i<70;i++){var sx=(i*83)%w,sy=(i*47)%Math.max(1,h*.62);g.globalAlpha=.25+.3*((i*17)%10)/10;g.fillStyle='#fff';g.beginPath();g.arc(sx,sy,(i%3)+.5,0,6.283);g.fill()}var R=Math.min(w,h)*.31,mx=w*.18,my=h*.77;var moon=g.createRadialGradient(mx-R*.35,my-R*.5,0,mx,my,R);moon.addColorStop(0,'#f9ffff');moon.addColorStop(.55,'#c9e7f4');moon.addColorStop(1,'#6d91a8');g.globalAlpha=1;g.fillStyle=moon;g.beginPath();g.arc(mx,my,R,0,6.283);g.fill();for(var q=0;q<9;q++){var cx=mx+Math.cos(q*2.7)*R*.65,cy=my+Math.sin(q*1.8)*R*.6,cr=R*(.035+(q%4)*.018);g.fillStyle='rgba(72,104,125,.2)';g.beginPath();g.arc(cx,cy,cr,0,6.283);g.fill()}
    function robot(x,y,s,dir){g.save();g.translate(x,y);g.scale(dir*s,s);g.fillStyle='#24435d';g.strokeStyle='#6ee7ff';g.lineWidth=1.4;g.fillRect(-10,-12,20,16);g.strokeRect(-10,-12,20,16);g.fillStyle='#06152b';g.fillRect(-6,-8,12,6);g.fillStyle='#6ee7ff';g.fillRect(-4,-7,3,2);g.fillRect(2,-7,3,2);g.fillStyle='#4c728c';g.fillRect(-13,4,8,5);g.fillRect(5,4,8,5);g.fillRect(-9,9,5,8);g.fillRect(4,9,5,8);g.restore()}
    for(var r=0;r<4;r++){var rx=((t*(22+r*7)+r*120)%(w*.65))+w*.2,ry=h*.72-Math.abs(Math.sin(t*2+r))*4;robot(rx,ry,1+r*.12,r%2?-1:1)}
    function ufo(x,y,s){g.save();g.translate(x,y);g.fillStyle='#384d62';g.beginPath();g.ellipse(0,5,34*s,9*s,0,0,6.283);g.fill();g.fillStyle='#8beaff';g.beginPath();g.ellipse(0,-1,17*s,9*s,0,Math.PI,6.283);g.fill();g.fillStyle='#d65cff';g.globalAlpha=.75;g.fillRect(-20*s,5,40*s,3*s);g.globalAlpha=1;g.strokeStyle='#fff';g.beginPath();g.moveTo(-12*s,9*s);g.lineTo(-18*s,28*s);g.moveTo(12*s,9*s);g.lineTo(18*s,28*s);g.stroke();g.restore()}
    ufo(w*.7,h*.22,1);ufo(w*.87,h*.35,.7);
    function alien(x,y,s){g.save();g.translate(x,y);g.scale(s,s);g.fillStyle='#6b4a8f';g.strokeStyle='#d982ff';g.beginPath();g.ellipse(0,0,10,13,0,0,6.283);g.fill();g.stroke();g.fillStyle='#06152b';g.beginPath();g.ellipse(-4,-3,2.5,4,0,0,6.283);g.ellipse(4,-3,2.5,4,0,0,6.283);g.fill();g.strokeStyle='#ff67a7';g.beginPath();g.moveTo(-6,7);g.lineTo(-12,15);g.moveTo(6,7);g.lineTo(12,15);g.stroke();g.restore()}
    alien(w*.62,h*.79,1.1);alien(w*.77,h*.76,.9);alien(w*.9,h*.81,1.2);g.globalAlpha=.55;g.strokeStyle='#a9edff';g.lineWidth=2;g.beginPath();g.moveTo(w*.7,h*.25);g.lineTo(w*.65,h*.75);g.moveTo(w*.87,h*.38);g.lineTo(w*.9,h*.76);g.stroke();g.globalAlpha=1;}
  window.drawTitleBg=drawTitleBg;
  function boot(){var link=document.querySelector('link[data-robot-theme]');if(!link){link=document.createElement('link');link.rel='stylesheet';link.href='robot-theme.css';link.dataset.robotTheme='1';document.head.appendChild(link)}replaceVisibleText();applyMapThemes();try{if(typeof window.bakeBlocked==='function')window.bakeBlocked()}catch(e){}try{window.bakeLandmark();window.bakeMapDecos()}catch(e){}try{window.drawTitleBg(performance.now()/1000)}catch(e){}var title=document.querySelector('#s-title .tag');if(title)title.textContent='Earth is under attack. Deploy the robots. Hold the line.';}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else setTimeout(boot,0);setTimeout(boot,1200);
})();